#! /bin/sh
#
# moveto - Move current window to top-right corner
#

x_offset="23"

read x_max y_max <<< $(xdotool getdisplaygeometry)

eval "$(xdotool getactivewindow getwindowgeometry --shell)"

xdotool windowmove $WINDOW $(($x_max - $WIDTH + $x_offset)) 0
