#! /bin/sh

self="$(xdotool getactivewindow)"
xdotool windowmove --sync --relative ${self} -1 1
gnome-terminal -q --geometry=120x100-0+0 --window --tab
while [[ "${self}" == "$(xdotool getactivewindow)" ]]; do
	sleep 0.1
done
xdotool windowclose ${self}
