#! /bin/sh
#
# find-unowned -- Find files not owned by any pacman package.
#                 Recursively descends from the current directory.
#

sudo find $(pwd) -type f | while read -r file; do 
    pacman -Qo "$file" >/dev/null 2>&1 || echo "$file" 
done
